name: E2E

on:
  workflow_dispatch:
  push:
    paths:
      - 'e2e/**'
      - 'playwright.config.ts'
      - '.github/workflows/e2e.yml'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ← ここが「Node セットアップ」。lock ファイルが無い環境でもコケない設定にしてある
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
        # ※ cache は lockfile が無いと失敗しがちなので明示的に使わない

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          E2E_BASE_URL: https://miyata-connect.github.io/walk-nav/
        run: npx playwright test --reporter=line
