name: places-proxy health

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ci/check_places.sh

      - name: Run places health check
        run: bash ci/check_places.sh
